# .github/workflows/deploy.yml

name: Lint and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20' # Cambia a la versión de Go que estés usando

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

    - name: Run golangci-lint
      run: |
        golangci-lint run

    - name: Deploy to Render
      if: success()
      env:
        RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        curl "$RENDER_DEPLOY_HOOK_URL"